// <auto-generated />
namespace CBA.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AccountConfigSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountConfigSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202104210245565_AccountConfigSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
